---
- name: Prueba envio mail
  hosts: localhost
  vars:
    - notificar: "mail"
  tasks:
    - name: Envia mail desde google
      mail:
        host: smtp.gmail.com
        port: 587
        secure: starttls
        charset: utf-8
        sender: dherranzb@gmail.com
        username: dherranzb
        password: "{{password}}"
        to: dherranzb@gmail.com
        subject: "Esto es una prueba"
        body: "Esto ha salido de puta madre"
      delegate_to: localhost

      when: notificar == "mail"
    
    - name: Instalar pushbullet
      pip: 
        name: pushbullet.py 
      when: notificar == "pushbullet"

    - name: Enviar sms
      pushbullet:
        api_key: "api_key"
        device: "android"
        title: "notificacion"
      when: notificar == "pushbullet"
