---
- name: Instalación Grafana
  hosts: Windows
  gather_facts: no
  tasks:
    - name: Install_Grafana
      win_chocolatey:
        name: "grafana"
        state: present
    
    - name: Configure_Firewall for Grafana
      win_firewall_rule:
        name:       "Grafana server"
        localport:  "3000"
        action:     allow
        direction:  in
        protocol:   tcp
        state:      present
        enabled:    yes

    - block:
      - name: Start Grafana
        # Gruadamos la feinicion del servicio en una variable
        win_service: &start_grafana_service
          name: "grafana-server"
          description: "Grafana server"
          dependencies: [ "Tcpip" ]
          state: started
          start_mode: auto

      rescue:
      - name: Find Grafana
        win_find:
          patterns: 'grafana-server.exe'
          paths: 'C:\ProgramData\chocolatey\lib\grafana'
          recurse: yes
        register: _

      - name: Create Service Grafana
        win_nssm:
          name: "grafana-server"
          application: '{{_.files[0].path}}'

      - name: Start Grafana
        # Recuperamos la definicion del servicio
        win_service: *start_grafana_service

