---
- name: Instalación Grafana
  hosts: Windows
  gather_facts: no
  tasks:
    - name: Install_Grafana
      win_chocolatey:
        name: "grafana"
        state: present
    
    - name: Configure_Firewall for Grafana
      win_firewall_rule:
        name:       "Grafana server"
        localport:  "3000"
        action:     allow
        direction:  in
        protocol:   tcp
        state:      present
        enabled:    yes


    - name: Find Grafana
      win_find:
        patterns: 'grafana-server.exe'
        paths: 'C:\ProgramData\chocolatey\lib\grafana'
        recurse: yes
      reguster: _

    - name: Install NSSM
      win_chocolatey:
        name: "nssm"
        state: present

    - name: Create Service for Grafana
      tags: "service"
      win_nssm:
        name: "grafana-server"
        application: '{{_.files[0].path}}'

    - name: Activate Grafana Service
      win_service:
        name: "grafana_server"
        description: "Grafana server"
        dependencies: [ "Tcpip"]
        state: started
        start_mode: auto
