---
- name: Primer play
  hosts: localhost
  become: True
  tasks:
          - name: Instalar vim
            yum: name=vim state=latest
          - include: instalar_apache2.yml, lll
...            
