---
- name: Actualizar configuracion sshd_config
  hosts: localhost
  connection: local
  become: True
  tasks:
          - name: Copiar fichero
            copy: src=ssh_config dest=/etc/ssh/ssh_config
            notify: restart_sshd

  handlers:
          - name: restart_sshd
            service: name=sshd state=restarted
...
