---
- name: Prueba para parar tomcat
  hosts: Windows
  tasks:

    - name: Parar tomcat en windows
      win_command: C:\scripts\controlm\refrendollamadas\0017_REFRENDOLLAMADAS_TOMCAT.cmd
      tags: [ "con_script" ]

    - name: Parar servicio

      win_service:
        name: Tomcat9
        state: stopped
       
      tags: [ "parada" ]
    
    - name: Arrancar servicio
      
      win_service:
        name: Tomcat9
        state: started
      
      tags: [ "arranque" ]  


