---
- name: Prueba para parar tomcat
  hosts: 192.168.1.38
  tasks:
    - name: Parar tomcat en windows
      win_shell:
      args:
      
        exectuable: c:\script\controlm\refrendollamadas\0017_REFRENDOLLAMADAS_TOMCAT.cmd
      


