---
- name: Prueba para parar tomcat
  hosts: 192.168.1.38
  tasks:
    - name: Parar tomcat en windows
      ansible.windows.win_shell:
        exectuable: c:\script\controlm\refrendollamadas\0017_REFRENDOLLAMADAS_TOMCAT
      


