---
- name: Prueba para parar tomcat
  hosts: Windows
  gather_facts: false 
  vars:
   error: true 

  tasks:

    - block:
      - name: Parar tomcat utilizando script vb
        win_command: C:\scripts\controlm\refrendollamadas\0017_REFRENDOLLAMADAS_TOMCAT.cmd
        tags: [ "con_script" ]
      
      - name: Parar servicio
        win_service:
          name: Tomcat91
          state: stopped
        tags: [ "parada" ]
        register: parada

      - name: Output del servicio  
        debug:
          msg: "{{ parada.display_name }} {{ parada.state }}"
        tags: [ "parada" ]

      - name: Arrancar servicio
        win_service:
          name: Tomcat9
          state: started
        tags: [ "arranque" ]  
        register: arranque

      - name: Output del servicio
        debug:
          msg: "{{ arranque.display_name }} {{ arranque.state }}"
        tags: [ "arranque" ]

      - name: Envia Correo ok
        - include: envio_correo.yml
        # - debug: msg="Correo Ok"
        #- import_tasks: "envio_correo.yml"
        when: error == parada.changed | arranque.changed

      rescue:

      - name: Envia correo NO OK
        - include: envio_correo.yml
        when: error != parada.chanaged | arranque.changed
              #- debug: msg="Correo KO"
        #- import_tasks: "envio_correo.yml"

        

    


