---
- name: Prueba para parar tomcat
  hosts: 192.168.1.38
  tasks:
    - name: Parar tomcat en windows
      win_command: C:\scripts\controlm\refrendollamadas\0017_REFRENDOLLAMADAS_TOMCAT.cmd
      


